const superheroes = [
  "Barbara Gordon",
  "Batgirl",
  "Batwoman",
  "Big Barda",
  "Black Canary",
  "Black Cat",
  "Black Panther",
  "Captain Britain",
  "Doctor Strange",
  "Falcon",
  "Green Arrow",
  "Green Lantern",
  "Hawkeye",
  "Hellboy",
  "Human Torch",
  "Iceman",
  "Iron Fist",
  "Luke Cage",
  "Moon Knight",
  "Namor",
  "Nightcrawler",
  "Nova",
  "Plastic Man",
  "Red Hood",
  "Red Robin",
  "Red Tornado",
  "Rocket Raccoon",
  "Shazam",
  "Spawn",
  "Static Shock",
  "Swamp Thing",
  "The Atom",
  "The Punisher",
  "Vision",
  "War Machine",
  "Zatara",
  "Black Orchid",
  "Black Widow",
  "Captain America",
  "Captain Marvel",
  "Cassandra Cain",
  "Catwoman",
  "Domino",
  "Elektra",
  "Emma Frost",
  "Firestar",
  "Gamora",
  "Gwen Stacy",
  "Harley Quinn",
  "Hawkgirl",
  "Hulk",
  "Huntress",
  "Invisible Woman",
  "Iron Man",
  "Jean Grey",
  "Jessica Jones",
  "Jubilee",
  "Kate Bishop",
  "Kitty Pryde",
  "Lady Deathstrike",
  "Mera",
  "Mary Jane Watson",
  "Miss Martian",
  "Mockingbird",
  "Mystique",
  "Oracle",
  "Poison Ivy",
  "Power Girl",
  "Psylocke",
  "Raven",
  "Rogue",
  "Scarlet Witch",
  "She-Hulk",
  "Silver Sable",
  "Spider-Man",
  "Star Sapphire",
  "Starfire",
  "Stephanie Brown",
  "Storm",
  "Squirrel Girl",
  "Supergirl",
  "Superman",
  "The Flash",
  "Thor",
  "Tigra",
  "Vixen",
  "Wasp",
  "Wolverine",
  "Wonder Woman",
  "X-23",
  "Zatanna",
];
export default superheroes